// ─── Asset Loader ───
// Centralized asset loading with progress tracking.
// Manages sprite sheet generation and any future asset loading.

import * as THREE from 'three';
import { generateSpriteSheet } from '../assets/SpriteGenerator';
import type { SpriteSheetConfig } from '../assets/SpriteGenerator';

// ─── Types ───

export type LoadProgressCallback = (progress: number, stage: string) => void;

export interface LoadedAssets {
  spriteSheet: {
    texture: THREE.CanvasTexture;
    canvas: HTMLCanvasElement;
    config: SpriteSheetConfig;
  };
}

// ─── Asset Loader ───

export class AssetLoader {
  private onProgress: LoadProgressCallback | null = null;
  private assets: LoadedAssets | null = null;

  // ─── Progress ───

  setProgressCallback(cb: LoadProgressCallback): void {
    this.onProgress = cb;
  }

  private reportProgress(progress: number, stage: string): void {
    this.onProgress?.(Math.min(100, Math.max(0, progress)), stage);
  }

  // ─── Loading ───

  /**
   * Load all game assets. Returns when complete.
   */
  async loadAll(): Promise<LoadedAssets> {
    // Stage 1: Generate sprite sheet
    this.reportProgress(10, 'Generating character sprites...');
    await this.delay(50); // yield to UI

    const { canvas, config } = generateSpriteSheet('#ffffff');

    this.reportProgress(30, 'Creating textures...');
    await this.delay(50);

    const texture = new THREE.CanvasTexture(canvas);
    texture.magFilter = THREE.NearestFilter;
    texture.minFilter = THREE.NearestFilter;
    texture.colorSpace = THREE.SRGBColorSpace;

    // Stage 2: Block textures are generated by TextureAtlas (already in ChunkManager)
    this.reportProgress(50, 'Preparing block textures...');
    await this.delay(50);

    // Stage 3: Preparing world
    this.reportProgress(70, 'Preparing world...');
    await this.delay(50);

    // Stage 4: Finalizing
    this.reportProgress(90, 'Finalizing...');
    await this.delay(50);

    this.assets = {
      spriteSheet: {
        texture,
        canvas,
        config,
      },
    };

    this.reportProgress(100, 'Ready!');
    return this.assets;
  }

  // ─── Accessors ───

  getAssets(): LoadedAssets | null {
    return this.assets;
  }

  // ─── Helpers ───

  private delay(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  // ─── Cleanup ───

  dispose(): void {
    if (this.assets) {
      this.assets.spriteSheet.texture.dispose();
      this.assets = null;
    }
  }
}